### PR TITLE
Setting up tests again

### PR DESCRIPTION
**Pull request by ashwanirathee**
- [x] should fix issue 1 & 3 of this checklist mentioned here : [Link](https://github.com/JuliaMusic/MusicProcessing.jl/issues/10#issuecomment-669778591) and setup tests

### CODE REVIEW

**Comment by Datseris** [comment]
we should move all tests to use github CI. can you please copy and use the files from here: https://github.com/JuliaDynamics/DrWatson.jl/tree/master/.github/workflows  

At the moment we don't have any documentation but that's okay.

**Comment by Datseris** [comment]
and remove appveyor / travis files

**Comment by Datseris** [comment]
ok i'll try to merge this tonight

**Comment by ashwanirathee** [comment]
Sure, It would be a good start if we can setup the tests right. It would make review work a lot easier.

**Pull request merged**
