### PR TITLE
Bugfixes, updates to remove warnings, & unit test improvements

### PR DESCRIPTION
**Pull request by gnadt**

### CODE REVIEW

**Comment by Datseris** [comment]
tests still fail, any chance to make them work in this PR? we could tag a release if that's the case...

**Comment by gnadt** [comment]
Looking into it, seems to be an issue with alsa_plugins_jll

**Comment by Datseris** [comment]
even if you can't make the tests pass this is still fantastic progress!!! 

But to release a new version we probably would need passing tests.

**Comment by gnadt** [comment]
Yeah no worries, I'm trying to figure out the alsa_plugins_jll issue, but I'm not familiar with Binary Builder, so it's slow

**Comment by gnadt** [comment]
Ok I figured that wouldn't work, may need to wait for a PortAudio fix: https://github.com/JuliaAudio/PortAudio.jl/pull/125

Alternatively, I can revert to `@eval import PortAudio`, but that's just avoiding issue instead of resolving

**Comment by Datseris** [comment]
I'll ask PortAudio devs to merge your PR. (In the meantime, please update that PR's description and bump project.toml version?)

**Comment by gnadt** [comment]
I don't think I should be the one deciding on a version bump for a package I'm not familiar with?

**Comment by gnadt** [comment]
@Datseris should be all set. I had to revert to using `@eval import PortAudio` like before because I don't think the issues in other packages causing it to fail on ubuntu-latest will be fixed anytime soon (or ever). Fixed a bunch of bugs so at least the readme examples all work now (in addition to the tests).

**Comment by gnadt** [comment]
@Datseris does this need anything else or are you just busy?

**Comment by Datseris** [comment]
Sorry, I was just busy, thanks for fixing this. I'll tag a new release now!

**Comment by gnadt** [comment]
Thank you!

**Comment by Datseris** [comment]
Well, thank YOU For fixing this !

**Comment by gnadt** [comment]
No problem, just wish I had seen #10 earlier! Also fyi, there are 2 CompatHelper PRs that can be closed, and maybe re-enable the CompatHelper workflow?

**Comment by Datseris** [comment]
I closed the PRs and registerer 2.0 in the general registry. Do you mind doing a PR that updates all the github workflows?

**Comment by gnadt** [comment]
Yep, no problem

**Pull request merged**
